[FlyingThings3D]
    [FlyingThings3D.train]
        root = '/project/cv-ws2425/lmb/data/FlyingThings3D/TRAIN'
    [FlyingThings3D.test]
        root = '/project/cv-ws2425/lmb/data/FlyingThings3D/TEST'

[Sintel]
    root = '/project/cv-ws2425/lmb/data/Sintel/data/training'

[FlyingChairs]
    root = '/project/cv-ws2425/lmb/data/FlyingChairs/data'
